In [1]:
from cowin_api import CoWinAPI
import pandas as pd
import numpy as np

In [2]:
cowin = CoWinAPI()

In [3]:
#list of all states and corresponding districts
allStates = cowin.get_states()
statesDf = pd.DataFrame(allStates['states'])
#display statesDf to get a list of all states, change stateId to get list of corresponding districts
stateId = 29
allDistricts = cowin.get_districts(stateId)
districtsDf = pd.DataFrame(allDistricts['districts'])

In [4]:
#Taking User Input
#Ensure the user inputs are added correctly. To see exact names of district and state, display statesDf and districtsDf
print("Input State Name")
state_input = input().lower()
print("\n")
print("Input District Name")
district_input = input().lower()
print("\n")
print("Input Pincode")
pincode_input = input().lower()
print("\n")
print("Input Date(format as dd-mm-yyyy)")
date_input = input().lower()
print("\n")
print("Input min age (18 or 45)")
min_age_input = input().lower()

Input State Name
Uttarakhand


Input District Name
Haridwar


Input Pincode
247667


Input Date(format as dd-mm-yyyy)
10-05-2021


Input min age (18 or 45)
18

In [5]:
#State information
states = cowin.get_states()
state = [i for i in states["states"] if state_input in i["state_name"].lower()]

In [6]:
#District Information
districts = cowin.get_districts(state[0]["state_id"])
district = [i for i in districts["districts"] if district_input in i["district_name"].lower()]

In [7]:
#Pulling information by district
district_id = str(district[0]['district_id'])
date = date_input
min_age_limit = int(min_age_input)
available_centers_district = cowin.get_availability_by_district(district_id, date, min_age_limit)

In [8]:
#Pulling information by pincode
pin_code_input = str(pincode_input)
date = str(date_input)
min_age_limit = int(min_age_input)
available_centers_pincode = cowin.get_availability_by_pincode(pin_code_input, date, min_age_limit)

In [9]:
#Function to get vaccine info
def createDf(listInput):
    dfNull = {"date": 'N/A',
              "vaccine": 'N/A',
              "name": 'N/A',
              "address": 'N/A',
              "district_name": 'N/A',
              "block_name": 'N/A',
              "pincode": 'N/A',
              "min_age_limit": 'N/A',
              "fee_type": 'N/A',
              "available_capacity": 'N/A',}
    if len(listInput) == 0:
        return pd.DataFrame(dfNull, index=[0])
    else:
        baseDict = listInput
        info = []
        for i in baseDict:
            relevantData = dict((key,value) for key, value in i.items() if key in ['name','fee_type', "sessions",
                                                                                   'address','block_name','district_name',
                                                                                   'pincode'])
            relevantData["available_capacity"] = relevantData["sessions"][0]["available_capacity"]
            relevantData["min_age_limit"] = relevantData["sessions"][0]["min_age_limit"]
            relevantData["vaccine"] = relevantData["sessions"][0]["vaccine"]
            relevantData["date"] = relevantData["sessions"][0]["date"]
            del relevantData["sessions"]
            info.append(relevantData)

        df = pd.DataFrame(info)
        df_final = df[["date", "vaccine", "name",
                       "address","district_name", "block_name", "pincode",
                       "min_age_limit", "fee_type", "available_capacity"]]
        return pd.DataFrame(df_final)

In [10]:
tablePinCode = createDf(available_centers_pincode["centers"])

In [11]:
tableDistrict = createDf(available_centers_district["centers"])

In [12]:
display(tablePinCode)

,date,vaccine,name,address,district_name,block_name,pincode,min_age_limit,fee_type,available_capacity
0,10-05-2021,COVISHIELD,BSM Inter Collage,Near BSM Tiraha,Haridwar,Roorkee,247667,18,Free,0
1,10-05-2021,COVISHIELD,Gandhi Mahila Shilp Inter Clg,Near BT Ganj Roorkee,Haridwar,Roorkee,247667,18,Free,0
2,10-05-2021,COVISHIELD,Anand Swa.Saras. Sishu. Mandir,South Civil Line Roorkee,Haridwar,Roorkee,247667,18,Free,0

In [13]:
display(tableDistrict)

,date,vaccine,name,address,district_name,block_name,pincode,min_age_limit,fee_type,available_capacity
0,10-05-2021,COVISHIELD,BRC LAKSAR,BRC LAKSAR,Haridwar,Laksar,247663,18,Free,0
1,10-05-2021,COVISHIELD,BSM Inter Collage,Near BSM Tiraha,Haridwar,Roorkee,247667,18,Free,0
2,10-05-2021,COVISHIELD,Prem Nagar Asharam 1,Ranipur,Haridwar,Bahadrabad,249407,18,Free,0
3,10-05-2021,COVISHIELD,Moolraj Inter College Ramnagar,Ramnagar,Haridwar,Roorkee,247665,18,Free,0
4,10-05-2021,COVISHIELD,BRC Bhagwanpur,BRC Bhagwanpur,Haridwar,Bhagwanpur,247661,18,Free,0
5,10-05-2021,COVISHIELD,Gandhi Mahila Shilp Inter Clg,Near BT Ganj Roorkee,Haridwar,Roorkee,247667,18,Free,0
6,10-05-2021,COVISHIELD,SHREE CEMENT,LAKSAR,Haridwar,Laksar,247663,18,Free,0
7,10-05-2021,COVISHIELD,Raghnath Mandir Jwalapur,Pandeywala Jwalapur,Haridwar,Bahadrabad,249407,18,Free,0
8,10-05-2021,COVISHIELD,RNI INTER COLLAGE BHAGWANPUR,BHAGWANPUR,Haridwar,Bhagwanpur,247661,18,Free,0
9,10-05-2021,COVISHIELD,Anand Swa.Saras. Sishu. Mandir,South Civil Line Roorkee,Haridwar,Roorkee,247667,18,Free,0
10,10-05-2021,COVISHIELD,Nagar Palika Hall Manglore,Manglore,Haridwar,Narsan,247656,18,Free,0
11,11-05-2021,COVISHIELD,Nagar Panchayat Hall Jhabreda,Jhabreda,Haridwar,Narsan,247665,18,Free,0
12,14-05-2021,COVISHIELD,Chaman Lal Coll. Landhora,Landhora,Haridwar,Narsan,247664,18,Free,59